language: linux

script:
 - ./hugo

deploy:
  provider: pages
  target-branch: master
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
